name: Lint PHP
on:
  pull_request:
    branches:
      - main
    types: [labeled]
    paths:
      - "**.php"
      - "!resources/js/**"
jobs:
  phpcs:
    if: contains(github.event.pull_request.labels.*.name, 'ready_for_review') && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]

    name: PHP Version:${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup cache
        uses: pat-s/always-upload-cache@v1.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: 🔎 Detect coding standard violations
        run: ./vendor/bin/pint --test --format=checkstyle | cs2pr --graceful-warnings
